TIME_STEP = 900 #seconds
JOULES_PER_KWH = 3600000

MAX_POWER_TO_GRID = 2500 # [W]
KWP = 5 # A x eta [m^2]
CAPACITY = 7*JOULES_PER_KWH
CONVERTER_MAX_POWER = 4000
STORAGE_EFFICIENCY = 0.92

CONVERTER_VALUE_MAP_FILE = r'../../Kennfeld_WR.CSV'
BATTERY_VALUE_MAP_FILE = r'../../BatterieKennfeldNeu_60s_Fl.mat'
